### ISSUE TITLE
docs on how to instantiate with a given language

### ISSUE THREAD

**Issue by sperand-io** [satismeter/nps-widget#1]
Hey there!

A mutual customer of ours would like to create the widget with a custom language via Segment.

just want to confirm, the option "language" will cause the widget to load w/ that language, correct?

```
window.satismeter({
    token: this.options.token,
    user: user,
    language: <lang>
  });
```

if so, we could tweak the segment integration to proxy identify calls' `context.locale` parameter. since our [spec](https://segment.com/docs/api/tracking/track/#special-context) requires standard locale strings there, it would be nice if we could have those resolve automatically, or use something like github.com/segmentio/locale-string to resolve to the full language names. if not, we can still make it work :)

**Comment by jsedlacek** [comment]
Hi @sperand-io, you're correct, the right option is "language".
I have created a pull request that allows to specify additional traits (including language).
https://github.com/segmentio/analytics.js-integrations/pull/521

The auto-detection from locale is a good idea, I might follow-up with additional pull request to support that. But for now merging the original pull request should fix the customers issue.

**Comment by jsedlacek** [comment]
The pull request has been merged. Closing this issue.

**Comment by sperand-io** [comment]
thanks @jsedlacek !!
