### ISSUE TITLE
Publish on `npm` properly?

### ISSUE THREAD

**Issue by gvilarino** [satismeter/nps-widget#2]
`npm i -D satismeter/nps-widget`

yeilds 

`"nps-widget": "satismeter/nps-widget",` in `package.json`

Expected behavior is be:
`"nps-widget": "^x.y.z",`

I really fail to understand why you aren't using the standard `npm` approach, which makes it impossible to pin a version.

Same with https://github.com/satismeter/satismeter-js

Can you please publish under `npm-widget` or `satismeter-npm-widget` (the latter being the standard if you want to group deps for a single namespace)

**Comment by jsedlacek** [comment]
@gvilarino We published https://github.com/satismeter/satismeter-loader as a standard way to install satismeter using npm (browserify or webpack).

I am closing this, as the `nps-widget` package is intended for internal use and it does not make much sense to be published on npm.
